services:
  - type: web
    name: colin-archive
    env: node
    buildCommand: npm install
    startCommand: node server.js
    routes:
      - type: rewrite
        source: /p/*
        destination: /post.html